# electrostatic_transducer.py
# earth-systems-physics
# CC0 — No Rights Reserved
#
# Electrostatic motor/actuator driven by piezoelectric quartz output.
# Signal chain: magnon -> phonon -> piezo voltage -> electrostatic force -> rotation
#
# Silicon MEMS rotor in electrostatic field from quartz electrodes.
# No magnets, no copper windings — charge-driven mechanical work
# from Earth-abundant materials.
#
# Couples to: multi_channel_coupling.py (piezo voltage source),
#             crystal_device_gradient.py (quartz resonator specs),
#             layer_0b_magnomechanical.py (geomagnetic signal input)

import numpy as np

# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────

HBAR      = 1.0545718e-34       # reduced Planck constant (J·s)
K_B       = 1.380649e-23        # Boltzmann constant (J/K)
EPSILON_0 = 8.8541878128e-12    # permittivity of free space (F/m)
E_CHARGE  = 1.602176634e-19     # elementary charge (C)
MU_0      = 4 * np.pi * 1e-7   # permeability of free space (T·m/A)
GAMMA     = 1.7608597e11        # gyromagnetic ratio (rad/s/T)

# ─────────────────────────────────────────────
# SILICON PROPERTIES
# ─────────────────────────────────────────────

SILICON = {
    "epsilon_r":            11.7,       # relative permittivity
    "dielectric_strength":  30e6,       # V/m (breakdown field)
    "resistivity_intrinsic": 2300,      # Ohm·m at 300K
    "resistivity_doped":    0.01,       # Ohm·m (moderately doped)
    "density":              2329,       # kg/m^3
    "youngs_modulus":       170e9,      # Pa
    "poisson_ratio":        0.28,
    "c_sound_long":         8433,       # m/s longitudinal [100]
    "c_sound_shear":        5843,       # m/s shear [100]
    "thermal_conductivity": 148,        # W/(m·K) at 300K
    "thermal_expansion":    2.6e-6,     # 1/K
    "debye_temp":           645,        # K
    "bandgap_eV":           1.12,       # eV at 300K
    "electron_mobility":    0.145,      # m^2/(V·s)
    "hole_mobility":        0.045,      # m^2/(V·s)
    "oxide_thickness_nm":   2,          # native oxide SiO2
}

# Quartz piezo source (AT-cut resonator)
QUARTZ_PIEZO = {
    "d_26":       3.1e-12,      # piezo strain constant (C/N)
    "epsilon_r":  4.5,          # relative permittivity
    "k_sq":       0.0081,       # electromechanical coupling k^2
    "Q_mech":     1e6,          # mechanical Q at 300K
    "c_shear":    3764.0,       # shear wave speed (m/s)
    "rho":        2650.0,       # density (kg/m^3)
}


# ─────────────────────────────────────────────
# PIEZOELECTRIC VOLTAGE SOURCE
# ─────────────────────────────────────────────

def piezo_voltage_from_strain(strain, thickness_m, d_coeff=3.1e-12,
                               epsilon_r=4.5, Q_mech=1e6):
    """
    Voltage generated by piezoelectric quartz under mechanical strain.

    In open-circuit condition:
      V = d * stress * thickness / epsilon
      stress = strain * rho * c^2 (elastic)
      At resonance: strain_resonant = strain_static * Q

    strain      : mechanical strain (dimensionless)
    thickness_m : crystal thickness (m)
    d_coeff     : piezoelectric coefficient (C/N)
    epsilon_r   : relative permittivity
    Q_mech      : mechanical quality factor (amplification at resonance)
    returns     : dict with voltages and fields
    """
    rho = QUARTZ_PIEZO["rho"]
    c = QUARTZ_PIEZO["c_shear"]

    stress = strain * rho * c**2  # Pa
    # Piezo charge: q = d * stress * area
    # Open-circuit voltage: V = d * stress * t / (epsilon_0 * epsilon_r)
    V_static = d_coeff * stress * thickness_m / (EPSILON_0 * epsilon_r)
    V_resonant = V_static * Q_mech

    E_field_static = V_static / thickness_m
    E_field_resonant = V_resonant / thickness_m

    # Power available (at matched impedance)
    # P = V^2 / (4R), R = 1/(omega * C), C = epsilon * A / t
    f_res = QUARTZ_PIEZO["c_shear"] / (2 * thickness_m)
    omega = 2 * np.pi * f_res
    # For a 5mm diameter crystal
    A = np.pi * (2.5e-3)**2
    C_crystal = EPSILON_0 * epsilon_r * A / thickness_m
    Z_crystal = 1 / (omega * C_crystal) if omega > 0 else np.inf
    P_available = V_resonant**2 / (4 * Z_crystal) if Z_crystal > 0 else 0

    return {
        "V_static_V": V_static,
        "V_resonant_V": V_resonant,
        "E_field_static_Vm": E_field_static,
        "E_field_resonant_Vm": E_field_resonant,
        "stress_Pa": stress,
        "f_resonance_Hz": f_res,
        "C_crystal_F": C_crystal,
        "Z_crystal_ohm": Z_crystal,
        "P_available_W": P_available,
    }


def piezo_voltage_from_magnon(delta_B_T, fe_ppm=100, eta_cm=1.5,
                               thickness_m=0.1e-3, Q_mech=1e6):
    """
    Full signal chain: geomagnetic field variation -> piezo voltage.

    delta_B_T   : magnetic field perturbation (T)
    fe_ppm      : iron defect concentration in quartz
    eta_cm      : spin-phonon coupling strength (cm^-1)
    thickness_m : crystal thickness (m)
    Q_mech      : mechanical Q factor
    returns     : dict with full chain analysis
    """
    # Magnon frequency shift from field variation
    delta_omega_magnon = GAMMA * MU_0 * delta_B_T
    delta_f_magnon = delta_omega_magnon / (2 * np.pi)

    # Phonon frequency of crystal
    f_phonon = QUARTZ_PIEZO["c_shear"] / (2 * thickness_m)
    omega_phonon = 2 * np.pi * f_phonon

    # Crystal geometry
    diameter = 5e-3
    V_crystal = np.pi * (diameter/2)**2 * thickness_m

    # Spin-phonon coupling -> strain
    eta_Hz = eta_cm * 3e10
    eta_rad = 2 * np.pi * eta_Hz

    # Number of Fe ions
    N_fe = fe_ppm * 1e-6 * V_crystal * QUARTZ_PIEZO["rho"] * 6.022e23 / 0.060

    # Zero-point motion
    x_zpf = np.sqrt(HBAR / (2 * QUARTZ_PIEZO["rho"] * V_crystal * omega_phonon))

    # Per-ion coupling to phonon mode
    a_0 = 4.9e-10  # quartz lattice parameter
    g_sp_per_ion = eta_rad * x_zpf / a_0

    # Collective coupling
    g_sp_collective = g_sp_per_ion * np.sqrt(max(N_fe, 1))

    # Magnon linewidth (dilute spins)
    H_earth = 5e-5  # T baseline
    gamma_m = 0.1 * GAMMA * MU_0 * H_earth  # alpha=0.1 for Fe in quartz

    # Phonon linewidth
    gamma_b = omega_phonon / Q_mech

    # Driven phonon displacement from magnon perturbation
    # x = g_collective * delta_omega / (detuning * gamma_b) * x_zpf
    # At resonance (detuning ~ gamma_b): x ~ g_collective * delta_omega / gamma_b^2 * x_zpf
    x_driven = g_sp_collective * delta_omega_magnon / (gamma_b * omega_phonon) * x_zpf

    # Strain from driven displacement
    strain = x_driven / thickness_m

    # Get piezo voltage
    piezo = piezo_voltage_from_strain(strain, thickness_m, Q_mech=Q_mech)

    return {
        "delta_B_T": delta_B_T,
        "delta_f_magnon_Hz": delta_f_magnon,
        "N_fe_ions": N_fe,
        "g_sp_collective_Hz": g_sp_collective / (2 * np.pi),
        "x_driven_m": x_driven,
        "strain": strain,
        "V_piezo_V": piezo["V_resonant_V"],
        "E_field_Vm": piezo["E_field_resonant_Vm"],
        "P_available_W": piezo["P_available_W"],
        "f_resonance_Hz": piezo["f_resonance_Hz"],
    }


# ─────────────────────────────────────────────
# ELECTROSTATIC MOTOR / ACTUATOR
# ─────────────────────────────────────────────

def parallel_plate_force(V, gap_m, area_m2, epsilon_r=1.0):
    """
    Electrostatic force between parallel plates.
    F = epsilon_0 * epsilon_r * A * V^2 / (2 * d^2)

    V       : voltage across gap (V)
    gap_m   : plate separation (m)
    area_m2 : plate overlap area (m^2)
    epsilon_r: dielectric constant of gap material
    returns : dict with force, pressure, energy
    """
    F = EPSILON_0 * epsilon_r * area_m2 * V**2 / (2 * gap_m**2)
    pressure = F / area_m2 if area_m2 > 0 else 0
    E_stored = 0.5 * EPSILON_0 * epsilon_r * area_m2 * V**2 / gap_m

    # Breakdown check
    E_field = V / gap_m
    E_breakdown = SILICON["dielectric_strength"]
    safe = E_field < E_breakdown

    return {
        "force_N": F,
        "pressure_Pa": pressure,
        "E_stored_J": E_stored,
        "E_field_Vm": E_field,
        "below_breakdown": safe,
        "margin_to_breakdown": E_breakdown / E_field if E_field > 0 else np.inf,
    }


def comb_drive_force(V, n_fingers, finger_length_m, gap_m,
                     thickness_m, epsilon_r=1.0):
    """
    MEMS comb drive — the workhorse electrostatic actuator.
    Force is CONSTANT with displacement (unlike parallel plate).

    F = n * epsilon_0 * epsilon_r * t * V^2 / gap

    n_fingers      : number of finger pairs
    finger_length_m: finger overlap length (m)
    gap_m          : gap between fingers (m)
    thickness_m    : device layer thickness (m)
    returns        : dict with force, displacement per volt^2
    """
    F = n_fingers * EPSILON_0 * epsilon_r * thickness_m * V**2 / gap_m

    # Capacitance
    C = 2 * n_fingers * EPSILON_0 * epsilon_r * thickness_m * finger_length_m / gap_m

    # Energy
    E = 0.5 * C * V**2

    # Displacement (for a spring-loaded comb drive)
    # x = F / k, but k depends on suspension design
    # Typical MEMS spring: k ~ 0.1 - 10 N/m
    # We'll compute force per unit spring constant
    force_per_k = F  # displacement = F/k, so x = force_per_k / k

    return {
        "force_N": F,
        "capacitance_F": C,
        "E_stored_J": E,
        "force_per_k_m_N_per_m": force_per_k,
        "n_fingers": n_fingers,
    }


def electrostatic_rotor(V, n_poles, rotor_radius_m, gap_m,
                         rotor_thickness_m, rotor_length_m):
    """
    Electrostatic variable-capacitance motor.
    Torque from changing capacitance as rotor turns.

    tau = 0.5 * n_poles * epsilon_0 * (rotor_length / gap) * V^2

    V               : drive voltage (V)
    n_poles         : number of pole pairs
    rotor_radius_m  : rotor radius (m)
    gap_m           : air gap (m)
    rotor_thickness_m: radial thickness (m)
    rotor_length_m  : axial length (m)
    returns         : dict with torque, power, speed
    """
    # Capacitance variation per pole
    dC_dtheta = EPSILON_0 * rotor_length_m * rotor_thickness_m / gap_m

    # Torque
    torque = 0.5 * n_poles * dC_dtheta * V**2

    # Moment of inertia (thin cylindrical shell)
    rho_si = SILICON["density"]
    m_rotor = rho_si * 2 * np.pi * rotor_radius_m * rotor_thickness_m * rotor_length_m
    I_rotor = m_rotor * rotor_radius_m**2

    # Angular acceleration
    alpha_acc = torque / I_rotor if I_rotor > 0 else 0

    # Steady-state speed estimate (limited by air drag at MEMS scale)
    # Drag torque ~ eta * omega * r^3 * L (viscous)
    # At atmospheric pressure: eta_air ~ 1.8e-5 Pa·s
    eta_air = 1.8e-5
    drag_coeff = eta_air * rotor_radius_m**3 * rotor_length_m
    omega_ss = torque / drag_coeff if drag_coeff > 0 else 0
    rpm_ss = omega_ss * 60 / (2 * np.pi)

    # Mechanical power at steady state
    P_mech = torque * omega_ss

    # Electrical power input
    # Switching loss: P = 0.5 * C_total * V^2 * f_switching
    C_total = n_poles * EPSILON_0 * rotor_length_m * rotor_thickness_m / gap_m
    f_switch = n_poles * omega_ss / (2 * np.pi)
    P_elec = 0.5 * C_total * V**2 * f_switch

    efficiency = P_mech / P_elec if P_elec > 0 else 0

    return {
        "torque_Nm": torque,
        "m_rotor_kg": m_rotor,
        "I_rotor_kgm2": I_rotor,
        "alpha_rad_s2": alpha_acc,
        "omega_steady_rad_s": omega_ss,
        "rpm_steady": rpm_ss,
        "P_mechanical_W": P_mech,
        "P_electrical_W": P_elec,
        "efficiency": min(efficiency, 1.0),
        "C_total_F": C_total,
    }


# ─────────────────────────────────────────────
# MEMS DEVICE CONFIGURATIONS
# ─────────────────────────────────────────────

def config_mems_micro(V_drive=1.0):
    """
    Micro-scale MEMS electrostatic motor.
    Typical silicon MEMS: 100um rotor, 2um gap, 50 poles.
    """
    return electrostatic_rotor(
        V=V_drive,
        n_poles=50,
        rotor_radius_m=50e-6,
        gap_m=2e-6,
        rotor_thickness_m=10e-6,
        rotor_length_m=20e-6,
    )


def config_mems_milli(V_drive=10.0):
    """
    Milli-scale electrostatic motor.
    Larger: 1mm rotor, 10um gap, 100 poles.
    More torque, lower speed.
    """
    return electrostatic_rotor(
        V=V_drive,
        n_poles=100,
        rotor_radius_m=500e-6,
        gap_m=10e-6,
        rotor_thickness_m=50e-6,
        rotor_length_m=200e-6,
    )


def config_macro_disk(V_drive=100.0):
    """
    Macro-scale electrostatic disk motor.
    1cm rotor, 100um gap, 200 poles.
    Requires higher voltage but produces usable torque.
    """
    return electrostatic_rotor(
        V=V_drive,
        n_poles=200,
        rotor_radius_m=5e-3,
        gap_m=100e-6,
        rotor_thickness_m=500e-6,
        rotor_length_m=1e-3,
    )


# ─────────────────────────────────────────────
# FULL SIGNAL CHAIN: GEOMAGNETIC -> MECHANICAL
# ─────────────────────────────────────────────

def full_transduction_chain(
    delta_B_T=500e-9,           # geomagnetic storm ~500 nT
    fe_ppm=100,                 # Fe concentration in quartz
    eta_cm=1.5,                 # spin-phonon coupling (cm^-1)
    quartz_thickness_m=0.1e-3,  # 100 um AT-cut quartz
    Q_mech=1e6,                 # mechanical Q
    motor_config="mems_micro",  # motor size
):
    """
    Complete signal chain from geomagnetic variation to mechanical work.

    1. Geomagnetic dB -> magnon frequency shift (Layer 0b)
    2. Spin-phonon coupling -> lattice vibration (magnonic)
    3. Piezoelectric effect -> voltage (quartz)
    4. Electrostatic force -> rotor torque (silicon MEMS)
    5. Rotation -> mechanical work

    Returns dict with full chain analysis and efficiency at each stage.
    """
    # Stage 1-3: Geomagnetic -> piezo voltage
    piezo = piezo_voltage_from_magnon(
        delta_B_T=delta_B_T,
        fe_ppm=fe_ppm,
        eta_cm=eta_cm,
        thickness_m=quartz_thickness_m,
        Q_mech=Q_mech,
    )

    V_piezo = piezo["V_piezo_V"]

    # Stage 4: Piezo voltage -> electrostatic motor
    if motor_config == "mems_micro":
        motor = config_mems_micro(V_drive=V_piezo)
    elif motor_config == "mems_milli":
        motor = config_mems_milli(V_drive=V_piezo)
    elif motor_config == "macro_disk":
        motor = config_macro_disk(V_drive=V_piezo)
    else:
        motor = config_mems_micro(V_drive=V_piezo)

    # Energy accounting
    E_magnetic = HBAR * GAMMA * MU_0 * delta_B_T  # energy per magnon perturbation
    E_mechanical = motor["P_mechanical_W"] / max(piezo["f_resonance_Hz"], 1)

    # Overall efficiency
    eta_overall = E_mechanical / E_magnetic if E_magnetic > 0 else 0

    # Minimum detectable field change (motor produces measurable rotation)
    # Thermal noise torque: tau_th = sqrt(4 k_B T gamma_drag / omega)
    eta_air = 1.8e-5
    r = 50e-6 if motor_config == "mems_micro" else 500e-6 if motor_config == "mems_milli" else 5e-3
    drag_coeff = eta_air * r**3 * r  # rough
    tau_thermal = np.sqrt(4 * K_B * 300 * drag_coeff)
    # Motor torque must exceed thermal noise
    # tau_motor = 0.5 * n * dC/dtheta * V^2
    # V_min where tau_motor = tau_thermal
    n_poles = motor.get("C_total_F", 1e-15) / max(EPSILON_0, 1e-30)  # rough
    V_min_detect = np.sqrt(2 * tau_thermal / max(motor["torque_Nm"] / max(V_piezo**2, 1e-30), 1e-30))

    # What geomagnetic field change produces V_min_detect?
    # V_piezo scales linearly with delta_B (through the chain)
    sensitivity = V_piezo / delta_B_T if delta_B_T > 0 else 0
    B_min_detect = V_min_detect / sensitivity if sensitivity > 0 else np.inf

    return {
        "input": {
            "delta_B_T": delta_B_T,
            "fe_ppm": fe_ppm,
            "eta_spin_phonon_cm": eta_cm,
            "Q_mech": Q_mech,
            "motor_config": motor_config,
        },
        "stage_1_magnon": {
            "delta_f_magnon_Hz": piezo["delta_f_magnon_Hz"],
            "N_fe_ions": piezo["N_fe_ions"],
        },
        "stage_2_phonon": {
            "x_driven_m": piezo["x_driven_m"],
            "strain": piezo["strain"],
            "f_resonance_Hz": piezo["f_resonance_Hz"],
        },
        "stage_3_piezo": {
            "V_piezo_V": V_piezo,
            "P_available_W": piezo["P_available_W"],
        },
        "stage_4_motor": {
            "torque_Nm": motor["torque_Nm"],
            "rpm_steady": motor["rpm_steady"],
            "P_mechanical_W": motor["P_mechanical_W"],
            "efficiency": motor["efficiency"],
        },
        "overall": {
            "E_magnetic_J": E_magnetic,
            "E_mechanical_J": E_mechanical,
            "eta_overall": eta_overall,
            "V_sensitivity_V_per_T": sensitivity,
            "B_min_detectable_T": B_min_detect,
            "tau_thermal_Nm": tau_thermal,
        },
        "materials": {
            "quartz": "AT-cut SiO2 + Fe3+ defects (piezoelectric source)",
            "silicon": "MEMS rotor (electrostatic actuator)",
            "magnets": "NONE",
            "copper": "NONE (no windings)",
            "rare_earth": "NONE",
        },
    }


# ─────────────────────────────────────────────
# COUPLING STATE EXPORT
# ─────────────────────────────────────────────

def coupling_state(delta_B_T=500e-9, fe_ppm=100, eta_cm=1.5,
                   quartz_thickness_m=0.1e-3, Q_mech=1e6,
                   motor_config="mems_micro"):
    """
    State vector for coupling to other layers.
    Same interface contract as other coupling_state() functions.
    """
    chain = full_transduction_chain(
        delta_B_T=delta_B_T,
        fe_ppm=fe_ppm,
        eta_cm=eta_cm,
        quartz_thickness_m=quartz_thickness_m,
        Q_mech=Q_mech,
        motor_config=motor_config,
    )

    return {
        "V_piezo_V": chain["stage_3_piezo"]["V_piezo_V"],
        "P_available_W": chain["stage_3_piezo"]["P_available_W"],
        "torque_Nm": chain["stage_4_motor"]["torque_Nm"],
        "rpm_steady": chain["stage_4_motor"]["rpm_steady"],
        "P_mechanical_W": chain["stage_4_motor"]["P_mechanical_W"],
        "motor_efficiency": chain["stage_4_motor"]["efficiency"],
        "B_sensitivity_T": chain["overall"]["B_min_detectable_T"],
        "eta_overall": chain["overall"]["eta_overall"],
        "motor_config": motor_config,
    }


# ─────────────────────────────────────────────
# DEMO
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 80)
    print("ELECTROSTATIC TRANSDUCER — GEOMAGNETIC -> MECHANICAL")
    print("quartz(Fe) piezo -> silicon MEMS electrostatic motor")
    print("=" * 80)

    # Geomagnetic signals to test
    signals = [
        ("Diurnal variation",     50e-9),
        ("Geomagnetic storm",     500e-9),
        ("Pc1 pulsation",         1e-9),
        ("Solar wind shock",      100e-9),
    ]

    for config in ["mems_micro", "mems_milli", "macro_disk"]:
        print(f"\n{'─'*80}")
        print(f"  Motor config: {config}")
        print(f"{'─'*80}")
        print(f"  {'Signal':>25s}  {'dB (T)':>12s}  {'V_piezo':>12s}  "
              f"{'Torque (Nm)':>12s}  {'RPM':>12s}  {'P_mech (W)':>12s}")

        for name, dB in signals:
            chain = full_transduction_chain(delta_B_T=dB, motor_config=config)
            s3 = chain["stage_3_piezo"]
            s4 = chain["stage_4_motor"]
            print(f"  {name:>25s}  {dB:>12.4e}  {s3['V_piezo_V']:>12.4e}  "
                  f"{s4['torque_Nm']:>12.4e}  {s4['rpm_steady']:>12.4e}  "
                  f"{s4['P_mechanical_W']:>12.4e}")

    # Direct piezo voltage analysis
    print(f"\n{'─'*80}")
    print("  PIEZO VOLTAGE FROM EXTERNAL DRIVE")
    print(f"{'─'*80}")
    print(f"  {'V_drive':>10s}  {'Force (N)':>12s}  {'Torque':>12s}  "
          f"{'RPM':>12s}  {'P_mech':>12s}")
    for V in [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]:
        m = config_mems_milli(V_drive=V)
        print(f"  {V:>10.3f}  {m['torque_Nm']*1e3/0.5e-3:>12.4e}  "
              f"{m['torque_Nm']:>12.4e}  {m['rpm_steady']:>12.4e}  "
              f"{m['P_mechanical_W']:>12.4e}")

    print(f"\n{'─'*80}")
    print("  MATERIALS SUMMARY")
    print(f"{'─'*80}")
    chain = full_transduction_chain()
    for k, v in chain["materials"].items():
        print(f"    {k:15s}: {v}")

    print("\n" + "=" * 80)
    print("NO MAGNETS. NO COPPER. NO RARE EARTHS.")
    print("Quartz + silicon + iron defects + wire.")
    print("=" * 80)
