# model_collapse_guard.py
# earth-systems-physics
# CC0 — No Rights Reserved

"""
model_collapse_guard.py
───────────────────────
Detects conditions that lead to model collapse:

1. Synthetic data feeding back into training
2. Recursive generation without ground-truth anchoring
3. Financial forecast chains referencing only prior forecasts

Integrates conceptually with self_referential_guard.DependencyGraph
for grounding verification (same grounding logic applied to data
provenance instead of variable dependencies).

CC0 — No rights reserved. stdlib only.
"""

import math
from typing import Dict, List, Optional, Tuple, Set


# ═══════════════════════════════════════════════════════════
# LAYER 0: CONTAMINATION TRACKER
# ═══════════════════════════════════════════════════════════

class ContaminationTracker:
    """
    Tracks data provenance across generations.
    Each datum is either:
      - MEASURED:  from physical instrument / direct observation
      - DERIVED:   computed from other data (retains ancestor purity)
      - SYNTHETIC: generated by a model (contaminant)

    Collapse risk = f(synthetic_fraction, max_generation_depth,
                      longest_chain_without_measurement)
    """

    def __init__(self):
        self.sources: Dict[str, Dict] = {}

    def add_measured(self, name: str, instrument: str = ""):
        self.sources[name] = {
            "type": "MEASURED",
            "instrument": instrument,
            "generation": 0,
            "parents": [],
            "synthetic_ancestry": 0.0,
        }

    def add_derived(self, name: str, parents: List[str]):
        if not parents:
            raise ValueError(f"{name}: derived data must have parents")
        missing = [p for p in parents if p not in self.sources]
        if missing:
            raise ValueError(f"{name}: unknown parents {missing}")

        parent_records = [self.sources[p] for p in parents]
        max_gen = max(r["generation"] for r in parent_records)
        avg_synthetic = (
            sum(r["synthetic_ancestry"] for r in parent_records)
            / len(parent_records)
        )

        self.sources[name] = {
            "type": "DERIVED",
            "instrument": None,
            "generation": max_gen + 1,
            "parents": parents,
            "synthetic_ancestry": avg_synthetic,
        }

    def add_synthetic(self, name: str, model_name: str = "",
                      parents: Optional[List[str]] = None):
        parents = parents or []
        if parents:
            parent_records = [
                self.sources[p] for p in parents if p in self.sources
            ]
            max_gen = max(
                (r["generation"] for r in parent_records), default=0
            )
            prior_synthetic = max(
                (r["synthetic_ancestry"] for r in parent_records), default=0.0
            )
        else:
            max_gen = 0
            prior_synthetic = 0.0

        self.sources[name] = {
            "type": "SYNTHETIC",
            "instrument": f"model:{model_name}",
            "generation": max_gen + 1,
            "parents": parents,
            "synthetic_ancestry": min(1.0, (prior_synthetic + 1.0) / 2),
        }

    def collapse_risk(self) -> Dict:
        if not self.sources:
            return {"risk": "NONE", "reason": "No data tracked"}

        total = len(self.sources)
        synthetic_count = sum(
            1 for s in self.sources.values() if s["type"] == "SYNTHETIC"
        )
        synthetic_ratio = synthetic_count / total
        max_generation = max(s["generation"] for s in self.sources.values())
        max_synthetic_ancestry = max(
            s["synthetic_ancestry"] for s in self.sources.values()
        )

        # longest chain with no measurement
        longest_ungrounded = self._longest_ungrounded_chain()

        # risk = worst case across all dimensions
        risks: List[Tuple[str, str]] = []
        if synthetic_ratio > 0.6:
            risks.append((
                "CRITICAL",
                f"Synthetic ratio {synthetic_ratio:.0%} — "
                f"majority of data is model-generated",
            ))
        elif synthetic_ratio > 0.3:
            risks.append((
                "HIGH",
                f"Synthetic ratio {synthetic_ratio:.0%} — "
                f"contamination significant",
            ))
        elif synthetic_ratio > 0.1:
            risks.append((
                "MODERATE",
                f"Synthetic ratio {synthetic_ratio:.0%}",
            ))

        if max_generation > 4:
            risks.append((
                "CRITICAL",
                f"Generation depth {max_generation} — "
                f"deep recursion without anchor",
            ))
        elif max_generation > 2:
            risks.append((
                "HIGH",
                f"Generation depth {max_generation}",
            ))

        if longest_ungrounded > 3:
            risks.append((
                "CRITICAL",
                f"Longest ungrounded chain: {longest_ungrounded} steps",
            ))
        elif longest_ungrounded > 1:
            risks.append((
                "HIGH",
                f"Longest ungrounded chain: {longest_ungrounded} steps",
            ))

        if max_synthetic_ancestry > 0.8:
            risks.append((
                "HIGH",
                f"Max synthetic ancestry: {max_synthetic_ancestry:.0%}",
            ))

        if not risks:
            return {
                "risk": "LOW",
                "reasons": ["Within safe bounds"],
                "synthetic_ratio": round(synthetic_ratio, 3),
                "max_generation": max_generation,
                "recommendation": "Normal operation",
            }

        # worst risk wins
        severity_order = {"CRITICAL": 3, "HIGH": 2, "MODERATE": 1}
        worst = max(risks, key=lambda r: severity_order.get(r[0], 0))

        return {
            "risk": worst[0],
            "reasons": [r[1] for r in risks],
            "synthetic_ratio": round(synthetic_ratio, 3),
            "max_generation": max_generation,
            "longest_ungrounded_chain": longest_ungrounded,
            "max_synthetic_ancestry": round(max_synthetic_ancestry, 3),
            "recommendation": (
                "HALT — AUDIT GROUND TRUTH"
                if worst[0] == "CRITICAL"
                else "AUDIT GROUND TRUTH"
            ),
        }

    def _longest_ungrounded_chain(self) -> int:
        """Walk backwards from each node; count steps to nearest MEASURED."""
        longest = 0
        for name in self.sources:
            depth = self._depth_to_measurement(name, set())
            if depth > longest and depth < 999:
                longest = depth
        return longest

    def _depth_to_measurement(self, name: str, visited: Set[str]) -> int:
        if name in visited:
            return 999  # cycle — treat as ungrounded
        visited.add(name)
        record = self.sources.get(name)
        if not record:
            return 999
        if record["type"] == "MEASURED":
            return 0
        if not record["parents"]:
            return 999 if record["type"] == "SYNTHETIC" else 0
        parent_depths = [
            self._depth_to_measurement(p, visited.copy())
            for p in record["parents"]
        ]
        return min(parent_depths) + 1


# ═══════════════════════════════════════════════════════════
# LAYER 1: FORECAST CHAIN ANALYZER
# ═══════════════════════════════════════════════════════════

class ForecastChain:
    """
    Models a chain of predictions/forecasts.
    Each link is either:
      - anchored to a measurement
      - referencing another forecast

    Dependency tracking replaces keyword matching for grounding
    analysis.
    """

    def __init__(self):
        self.links: Dict[str, Dict] = {}

    def add_measurement(self, name: str, value: float, unit: str = ""):
        self.links[name] = {
            "type": "MEASUREMENT",
            "value": value,
            "unit": unit,
            "based_on": [],
        }

    def add_forecast(self, name: str, based_on: List[str],
                     value: Optional[float] = None):
        for dep in based_on:
            if dep not in self.links:
                raise ValueError(f"Unknown dependency: {dep}")
        self.links[name] = {
            "type": "FORECAST",
            "value": value,
            "based_on": based_on,
        }

    def analyze(self) -> Dict:
        """Classify the chain: how deep, how grounded."""
        if not self.links:
            return {"depth": 0, "grounded": True, "hazards": []}

        forecasts = {
            k: v for k, v in self.links.items() if v["type"] == "FORECAST"
        }
        measurements = {
            k: v for k, v in self.links.items() if v["type"] == "MEASUREMENT"
        }

        if not forecasts:
            return {
                "total_links": len(self.links),
                "measurements": len(measurements),
                "forecasts": 0,
                "max_depth": 0,
                "grounded": True,
                "hazards": [],
            }

        hazards: List[Dict] = []
        max_depth = 0
        for name in forecasts:
            depth, grounded = self._trace_depth(name, set())
            if depth > max_depth:
                max_depth = depth
            if not grounded:
                hazards.append({
                    "forecast": name,
                    "depth": depth,
                    "warning": (
                        f"'{name}' has no measurement in its ancestry"
                    ),
                })

        return {
            "total_links": len(self.links),
            "measurements": len(measurements),
            "forecasts": len(forecasts),
            "max_depth": max_depth,
            "grounded": len(hazards) == 0,
            "hazards": hazards,
        }

    def _trace_depth(self, name: str, visited: Set[str]) -> Tuple[int, bool]:
        """Returns (depth_to_measurement, is_grounded)."""
        if name in visited:
            return 999, False  # cycle
        visited.add(name)
        link = self.links[name]
        if link["type"] == "MEASUREMENT":
            return 0, True
        if not link["based_on"]:
            return 0, False  # forecast with no basis
        results = [
            self._trace_depth(dep, visited.copy())
            for dep in link["based_on"]
        ]
        min_depth = min(r[0] for r in results)
        any_grounded = any(r[1] for r in results)
        return min_depth + 1, any_grounded


# ═══════════════════════════════════════════════════════════
# DEMO
# ═══════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 60)
    print("MODEL COLLAPSE GUARD — DEMO")
    print("=" * 60)

    # ── 1. AI training data contamination ──
    print("\n── CONTAMINATION TRACKER ──")
    ct = ContaminationTracker()

    # ground truth
    ct.add_measured("satellite_imagery_2020", "Landsat-8")
    ct.add_measured("soil_sample_ph",         "pH meter")
    ct.add_measured("river_flow_gauge",       "USGS gauge station")

    # legitimate derivation
    ct.add_derived(
        "crop_health_index",
        ["satellite_imagery_2020", "soil_sample_ph"],
    )

    # synthetic generation starts
    ct.add_synthetic("ai_crop_forecast_v1",       "GPT-4",  ["crop_health_index"])
    ct.add_synthetic("ai_crop_forecast_v2",       "GPT-4",  ["ai_crop_forecast_v1"])
    ct.add_synthetic("ai_crop_forecast_v3",       "GPT-5",  ["ai_crop_forecast_v2"])
    ct.add_synthetic("ai_news_article",           "Claude", ["ai_crop_forecast_v3"])
    ct.add_synthetic("ai_training_data_from_news", "scraper", ["ai_news_article"])

    risk = ct.collapse_risk()
    print(f"  Risk: {risk['risk']}")
    for r in risk.get("reasons", []):
        print(f"    - {r}")
    print(f"  Recommendation: {risk['recommendation']}")

    # ── 2. Financial forecast chain ──
    print("\n── FORECAST CHAIN: GROUNDED ──")
    fc_good = ForecastChain()
    fc_good.add_measurement("measured_gdp_q1",    25.4,  "trillion USD")
    fc_good.add_measurement("measured_employment", 0.962, "ratio")
    fc_good.add_forecast(
        "gdp_q2_forecast",
        ["measured_gdp_q1", "measured_employment"],
        25.6,
    )
    result = fc_good.analyze()
    print(f"  Max depth: {result['max_depth']}, Grounded: {result['grounded']}")

    print("\n── FORECAST CHAIN: UNGROUNDED ──")
    fc_bad = ForecastChain()
    fc_bad.add_measurement("initial_rate", 0.05, "ratio")
    fc_bad.add_forecast("analyst_forecast",     ["initial_rate"])
    fc_bad.add_forecast("consensus_forecast",   ["analyst_forecast"])
    fc_bad.add_forecast("market_expectation",   ["consensus_forecast"])
    fc_bad.add_forecast("fed_forward_guidance", ["market_expectation"])
    fc_bad.add_forecast("next_rate_prediction", ["fed_forward_guidance"])
    result = fc_bad.analyze()
    print(f"  Max depth: {result['max_depth']}, Grounded: {result['grounded']}")
    if result["max_depth"] > 2:
        print(
            f"  WARNING: {result['max_depth']} layers of forecast-on-forecast"
        )
        print(
            f"  The measurement is {result['max_depth']} steps away from "
            f"the decision"
        )

    # ── 3. Contrast: indigenous knowledge chain ──
    print("\n── KNOWLEDGE CHAIN: LANDSCAPE ENCODING ──")
    fc_land = ForecastChain()
    fc_land.add_measurement("soil_observation_gen1", 1.0, "qualitative")
    fc_land.add_measurement("tree_growth_response",  1.0, "physical")
    fc_land.add_measurement("soil_observation_gen2", 1.0, "qualitative")
    fc_land.add_forecast(
        "planting_decision_gen3",
        ["soil_observation_gen1", "tree_growth_response",
         "soil_observation_gen2"],
    )
    result = fc_land.analyze()
    print(f"  Max depth: {result['max_depth']}, Grounded: {result['grounded']}")
    print(f"  Every generation re-measures — no recursion without anchor")
